  // RootLayout.js or wherever you're using the body tag
  import localFont from "next/font/local";
  import "./globals.css";
  import { TradeDataProvider } from "../app/components/TradeDataContext";
  import SocketProvider from "../../providers/SocketProvider";
  // import { GameStatusProvider } from "../../context/GameContext";
  import AuthProvider from "@/context/AuthProvider";

  // Fonts
  const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
  });
  const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
  });

  export const metadata = {
    title: "ProfitONN",
    description: "Generated by create next app",
  };

  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <head>
          {/* Add your meta tags or other head elements here */}
        </head>
        {/* Next.js will automatically handle the body, don't render another one */}
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* <AuthProvider> */}
            <SocketProvider>
              {/* <GameStatusProvider> */}
                <TradeDataProvider>{children}</TradeDataProvider>
              {/* </GameStatusProvider> */}
            </SocketProvider>
          {/* </AuthProvider> */}
        </body>
      </html>
    );
  }
